language: fortran

git:
   depth: 1

matrix:
   include:
   - os: linux
     sudo: required
     env: COVERAGE=true
   - os: linux
     sudo: required
     env: BUDS_OPT=3
   - os: osx

notifications:
   email:
      recipients:
         - nickpapior@gmail.com
      on_failure: always
      on_success: change

before_install:
   - .travis/before_install.sh

install:
   - .travis/install.sh

script:
   - .travis/script.sh

after_success:
   - if [[ ${COVERAGE:-false} != false ]]; then bash <(curl -s https://codecov.io/bash) ; fi
