# This distribution forces the compilation of
# the tool to enable storing the pre-processed
# sources.
.PHONY: dist
.NOTPARALLEL: dist
dist: libs
	@tools/dist.sh

# Local Variables:
#  mode: makefile-gmake
# End:
