_INCLUDED_common = 1

# Define default library names
BUDS_LIB_STATIC ?= libbuds.a
BUDS_LIB_SHARED ?= libbuds.so
BUDS_MODDIR ?= include

# Define common variables
_OCT_rw_r_r = 644
_OCT_rwx_rx_rx = 755

# Local Variables:
#  mode: makefile-gmake
# End:
