

# Include dir:
#    ./src/test
include $(TOP_DIR)/src/test/Makefile.inc


.PHONY: test tests
test: static
$(TESTS_OBJS): static
test: $(TESTS)
tests: test


# Local Variables:
#  mode: makefile-gmake
# End:
