module procedure BUD_TRANSFER_FUNC(copy,1Dto1D)
module procedure BUD_TRANSFER_FUNC(copy,2Dto1D)
module procedure BUD_TRANSFER_FUNC(copy,3Dto1D)
module procedure BUD_TRANSFER_FUNC(copy,4Dto1D)
module procedure BUD_TRANSFER_FUNC(copy,5Dto1D)

module procedure BUD_TRANSFER_FUNC(copy,1Dto2D)
module procedure BUD_TRANSFER_FUNC(copy,2Dto2D)
module procedure BUD_TRANSFER_FUNC(copy,3Dto2D)
module procedure BUD_TRANSFER_FUNC(copy,4Dto2D)
module procedure BUD_TRANSFER_FUNC(copy,5Dto2D)

module procedure BUD_TRANSFER_FUNC(copy,1Dto3D)
module procedure BUD_TRANSFER_FUNC(copy,2Dto3D)
module procedure BUD_TRANSFER_FUNC(copy,3Dto3D)
module procedure BUD_TRANSFER_FUNC(copy,4Dto3D)
module procedure BUD_TRANSFER_FUNC(copy,5Dto3D)

#undef BUD_TYPE_VAR_P