module procedure BUD_TRANSFER_FUNC(assoc,1Dto1D)
module procedure BUD_TRANSFER_FUNC(assoc,2Dto1D)
module procedure BUD_TRANSFER_FUNC(assoc,3Dto1D)
module procedure BUD_TRANSFER_FUNC(assoc,4Dto1D)
module procedure BUD_TRANSFER_FUNC(assoc,5Dto1D)

module procedure BUD_TRANSFER_FUNC(assoc,1Dto2D)
module procedure BUD_TRANSFER_FUNC(assoc,2Dto2D)
module procedure BUD_TRANSFER_FUNC(assoc,3Dto2D)
module procedure BUD_TRANSFER_FUNC(assoc,4Dto2D)
module procedure BUD_TRANSFER_FUNC(assoc,5Dto2D)

module procedure BUD_TRANSFER_FUNC(assoc,1Dto3D)
module procedure BUD_TRANSFER_FUNC(assoc,2Dto3D)
module procedure BUD_TRANSFER_FUNC(assoc,3Dto3D)
module procedure BUD_TRANSFER_FUNC(assoc,4Dto3D)
module procedure BUD_TRANSFER_FUNC(assoc,5Dto3D)

#undef BUD_TYPE_VAR_P